Prueba/Models/ProductoPrueba.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductoPrueba
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductoPrueba()
        {
            this.UsuarioProducto = new HashSet<UsuarioProducto>();
        }
    
        public int IdProducto { get; set; }
        public string NombreProducto { get; set; }
        public Nullable<int> CantidadDisponible { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioProducto> UsuarioProducto { get; set; }
    }
}

Prueba/Controllers/ProductoPruebaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Prueba.Datos;
using Prueba.Models;

namespace Prueba.Controllers
{
    public class ProductoPruebaController : Controller
    {
        //static string Conexion = "Persist Security Info=False;User ID=Ubd-Pru-appsweb;Password=Oprh73.6LnQw;Initial Catalog=LC-PRU-Enla_com;Server=TEST1\\CLBDSTEST01";
        ProductoDatos _ProductoDatos = new ProductoDatos();
        // GET: ProductoPrueba
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult Consultar()
        {
            var ListarProducto = _ProductoDatos.ListarProducto();
            return View(ListarProducto);
        }
        public ActionResult ConsultarCompraTotal()
        {
            var ListarCompras = _ProductoDatos.ListarCompras();
            return View(ListarCompras);
        }
        public ActionResult ConsultarCompraEfectiva()
        {
            int IdUsuario = Convert.ToInt32(Session["IdUsuario"]);
            var ListarProducto = _ProductoDatos.ConsultarCompraEfectiva(IdUsuario);
            return View(ListarProducto);
        }

        public ActionResult ConsultarCompra()
        {
            var ListarProducto = _ProductoDatos.ListarProducto();
            return View(ListarProducto);
        }
        
        public ActionResult HacerCompra(int IdProducto)
        {
            int IdUsuario = Convert.ToInt32(Session["IdUsuario"]);
            Session["IdProducto"] = IdProducto;
            var producto = _ProductoDatos.ConsultarProductoId(IdProducto);
            Session["CantidadDisponible"] = producto[0].CantidadDisponible;
            return View(producto);
            //var producto = _ProductoDatos.ComprarProducto(IdProducto, IdUsuario);
        }
        public class Cantidad
        {
            public int CantidadCompra { get; set; }
        }
        public ActionResult RealizarCompra(ListProducto producto)
        {
            int IdUsuario = Convert.ToInt32(Session["IdUsuario"]);
            int IdProducto = Convert.ToInt32(Session["IdProducto"]);
            int Cantidad = producto.CantidadComprar;
            if(Cantidad >= Convert.ToInt32(Session["CantidadDisponible"]))
            {
                ViewData["Mensaje"] = "Cantidad no disponible";
                return RedirectToAction("About");
            }
            else
            {
                var Compra = _ProductoDatos.ComprarProducto(IdProducto, IdUsuario, Cantidad);
                return RedirectToAction("ConsultarCompra");
            }
            
            
        }
        [HttpPost]
        public ActionResult Index(ListProducto producto)
        {
            if (!ModelState.IsValid)
                return View();

            var respuesta = _ProductoDatos.ResgistrarProducto(producto);
            return View(producto);
        }
        //[HttpPost]
        //public ActionResult Index(ListProducto producto)
        //{
        //    bool registrado;
        //    string mensaje;

        //    using (SqlConnection cn = new SqlConnection(Conexion))
        //    {
        //        SqlCommand cmd = new SqlCommand("spRegistrarProductoPrueba", cn);
        //        cmd.Parameters.AddWithValue("Nombre", producto.NombreProducto);
        //        cmd.Parameters.AddWithValue("Cantidad", producto.CantidadDisponible);
        //        cmd.Parameters.AddWithValue("Descripcion", producto.Descripcion);
        //        cmd.Parameters.Add("Registrado", SqlDbType.Bit).Direction = ParameterDirection.Output;
        //        cmd.CommandType = CommandType.StoredProcedure;

        //        cn.Open();
        //        cmd.ExecuteNonQuery();
        //        registrado = Convert.ToBoolean(cmd.Parameters["Registrado"].Value);
        //        mensaje = cmd.Parameters["Registrado"].Value.ToString();
        //    }
        //    if (mensaje.Equals(false))
        //    {
        //        ViewData["Mensaje"] = "Producto no pudo ser registrado";
        //    }
        //    else
        //    {
        //        ViewData["Mensaje"] = "Producto registrado con exito!";
        //    }

        //    if (registrado)
        //    {
        //        return RedirectToAction("About", "ProductoPrueba");
        //    }
        //    else
        //    {
        //        return View();
        //    }
        //}
        
        public ActionResult Actualizar(int IdProducto)
        {
            Session["IdProducto"] = IdProducto;
            var producto = _ProductoDatos.ConsultarProductoId(IdProducto);
            ViewData["Nombre"] = producto[0].NombreProducto;
            ViewData["Cantidad"] = producto[0].CantidadDisponible;
            ViewData["Descripcion"] = producto[0].Descripcion;

            return View(producto);
        }
        [HttpPost]
        public ActionResult Actualizar(ListProducto producto)
        {
            if (!ModelState.IsValid)
                return View();
            int IdProducto = Convert.ToInt32(Session["IdProducto"]);
            var respuesta = _ProductoDatos.ActualizarProducto(producto, IdProducto);
            if (respuesta)
            {
                return RedirectToAction("Consultar");
            }
            else
            {
                return View();
            }
        }
        public ActionResult Eliminar(int IdProducto)
        {
            var producto = _ProductoDatos.EliminarProducto(IdProducto);
            return RedirectToAction("Consultar");
        }
    }


}

Prueba/Views/ProductoPrueba/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Prueba/Views/ProductoPrueba/Actualizar.cshtml
@{
    ViewBag.Title = "Actualizar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <link href="~/Content/css/Login.css" rel="stylesheet" />
    <title>Actualizar Producto</title>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Actualizar Producto</h3>
                    </div>
                    <div class="panel-body">
                        @*<form asp-action="Actualizar" asp-controller="ProductoPrueba" method="post">*@
                        <form accept-charset="UTF-8" role="form" action="@Url.Action("Actualizar","ProductoPrueba")" method="post">
                            <input asp-for="IdProducto" type="hidden" class="form-control">
                            <fieldset>
                                @foreach (var item in Model)
                                {
                                    <div class="form-group">
                                        <input class="form-control" placeholder="Nombre Producto *" name="NombreProducto" type="text" maxlength="100" value="@ViewData["Nombre"]">
                                    </div>
                                    <div class="form-group">
                                        <input class="form-control" placeholder="Cantidad Disponible *" name="CantidadDisponible" type="number" maxlength="50" value="@ViewData["Cantidad"]">
                                    </div>
                                    <div class="form-group">
                                        <input class="form-control" placeholder="Descripción *" name="Descripcion" type="text" maxlength="100" value="@ViewData["Descripcion"]">
                                    </div>
                                }
                                <button class="btn btn-primary" type="submit">Actualizar</button>
                                <a asp-action="Consultar" asp-controller="ProductoPrueba" class="btn btn-warning" href="@Url.Action("Consultar","ProductoPrueba")">Consultar</a>
                            </fieldset>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
</body>
</html>

Prueba/Views/ProductoPrueba/Consultar.cshtml
@{
    ViewBag.Title = "Consultar";
    Layout = "~/Views/Shared/_Layout.cshtml";

}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <link href="~/Content/css/Login.css" rel="stylesheet" />
    <title>Listado de Productos</title>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-12 ">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Listado de Productos</h3>
                    </div>
                    <div class="panel-body">
                        <a href="@Url.Action("Index","ProductoPrueba")" class="btn btn-primary btn-sm">+ Producto</a>
                        <hr />
                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th>Id Producto</th>
                                    <th>Nombre Producto</th>
                                    <th>Cantidad Disponible</th>
                                    <th>Descripción Producto</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@item.IdProducto</td>
                                        <td>@item.NombreProducto</td>
                                        <td>@item.CantidadDisponible</td>
                                        <td>@item.Descripcion</td>
                                        <td>
                                            @Html.ActionLink("Actualizar", "Actualizar", "ProductoPrueba", new { IdProducto = item.IdProducto }, null)
                                        </td>
                                        <td>
                                            @Html.ActionLink("Eliminar", "Eliminar", "ProductoPrueba", new { IdProducto = item.IdProducto }, null)
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
</body>
</html>

Prueba/Views/ProductoPrueba/ConsultarCompra.cshtml
@{
    ViewBag.Title = "ConsultarCompra";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <link href="~/Content/css/Login.css" rel="stylesheet" />
    <title>Hacer Compras</title>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-12 ">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Hacer Compras</h3>
                    </div>

                    <div class="panel-body">
                        <hr />
                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th>Id Producto</th>
                                    <th>Nombre Producto</th>
                                    <th>Cantidad Disponible</th>
                                    <th>Descripción Producto</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@item.IdProducto</td>
                                        <td>@item.NombreProducto</td>
                                        <td>@item.CantidadDisponible</td>
                                        <td>@item.Descripcion</td>                                        
                                        <td>
                                            @Html.ActionLink("Comprar", "HacerCompra", "ProductoPrueba", new { IdProducto = item.IdProducto }, null)
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
</body>
</html>

Prueba/Views/ProductoPrueba/ConsultarCompraEfectiva.cshtml
@{
    ViewBag.Title = "ConsultarCompraEfectiva";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <link href="~/Content/css/Login.css" rel="stylesheet" />
    <title>Tus Compras</title>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-12 ">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Tus Compras</h3>
                    </div>
                    <div class="panel-body">
                        <hr />
                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th>Id Compra</th>
                                    <th>Código Comprador</th>
                                    <th>Comprador</th>
                                    <th>Código Producto</th>
                                    <th>Producto</th>
                                    <th>Cantidad Comprada</th>
                                    <th>Fecha Compra</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@item.IdUsuarioProducto</td>
                                        <td>@item.IdUsuario</td>
                                        <td>@item.Usuario</td>
                                        <td>@item.IdProducto</td>
                                        <td>@item.Producto</td>
                                        <td>@item.Cantidad</td>
                                        <td>@item.FechaCompra</td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
</body>
</html>

Prueba/Views/ProductoPrueba/ConsultarCompraTotal.cshtml
@{
    ViewBag.Title = "ConsultarCompraTotal";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <link href="~/Content/css/Login.css" rel="stylesheet" />
    <title>Total Compras</title>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-12 ">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Total Compras</h3>
                    </div>
                    <div class="panel-body">
                        <hr />
                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th>Id Compra</th>
                                    <th>Código Comprador</th>
                                    <th>Comprador</th>
                                    <th>Código Producto</th>
                                    <th>Producto</th>
                                    <th>Cantidad Comprada</th>
                                    <th>Fecha Compra</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                <tr>
                                    <td>@item.IdUsuarioProducto</td>
                                    <td>@item.IdUsuario</td>
                                    <td>@item.Usuario</td>
                                    <td>@item.IdProducto</td>
                                    <td>@item.Producto</td>
                                    <td>@item.Cantidad</td>
                                    <td>@item.FechaCompra</td>
                                </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
</body>
</html>

Prueba/Views/ProductoPrueba/Eliminar.cshtml
@{
    ViewBag.Title = "Eliminar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <link href="~/Content/css/Login.css" rel="stylesheet" />
    <title>Actualizar Producto</title>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Actualizar Producto</h3>
                    </div>
                    <div class="panel-body">
                        <form asp-action="Actualizar" asp-controller="ProductoPrueba" method="post">
                            <input asp-for="IdProducto" type="hidden" class="form-control">
                            <div class="alert alert-danger" role="alert">
                                @*Desea eliminar el producto? : @Html.DisplayTextFor(m => m.IdProducto) ?*@
                            </div>
                            <fieldset>
                                <button class="btn btn-danger" type="submit">Eliminar</button>
                                <a asp-action="Consultar" asp-controller="ProductoPrueba" class="btn btn-warning" href="@Url.Action("Consultar","ProductoPrueba")">Consultar</a>
                            </fieldset>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
</body>
</html>

Prueba/Views/ProductoPrueba/HacerCompra.cshtml
@{
    ViewBag.Title = "HacerCompra";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <link href="~/Content/css/Login.css" rel="stylesheet" />
    <title>Comprando ando!</title>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Comprando ando!</h3>
                    </div>
                    <div class="panel-body">
                        <div class="panel-body">
                            <form accept-charset="UTF-8" role="form" action="@Url.Action("RealizarCompra","ProductoPrueba")" method="post">

                                <hr />
                                <table class="table table-bordered">
                                    <thead>
                                        <tr>
                                            <th>Id Producto</th>
                                            <th>Nombre Producto</th>
                                            <th>Cantidad Disponible</th>
                                            <th>Descripción Producto</th>
                                            <th>Cantidad a Comprar</th>
                                            <th>Comprar</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model)
                                        {
                                            <tr>
                                                <td>@item.IdProducto</td>
                                                <td>@item.NombreProducto</td>
                                                <td>@item.CantidadDisponible</td>
                                                <td>@item.Descripcion</td>
                                                <td>
                                                    <input class="form-control" placeholder="Cantidad" name="CantidadComprar" type="number" value="">
                                                </td>
                                                <td>
                                                    <input class="btn btn-lg btn-primary btn-block" type="submit" value="Comprar">
                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
</body>
</html>

Prueba/Views/ProductoPrueba/Index.cshtml
@{
    Layout = null;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <link href="~/Content/css/Login.css" rel="stylesheet" />
    <title>Registrar Producto</title>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Registrar Producto</h3>
                    </div>
                    <div class="panel-body">
                        <form accept-charset="UTF-8" role="form" action="@Url.Action("Index","ProductoPrueba")" method="post">
                            <fieldset>
                                <div class="form-group">
                                    <input class="form-control" placeholder="Nombre Producto *" name="NombreProducto" type="text" maxlength="100" required>
                                </div>
                                <div class="form-group">
                                    <input class="form-control" placeholder="Cantidad Disponible *" name="CantidadDisponible" type="number" maxlength="50" required>
                                </div>
                                <div class="form-group">
                                    <input class="form-control" placeholder="Descripción *" name="Descripcion" type="text" maxlength="100" required>
                                </div>
                                <button class="btn btn-primary" type="submit">Guardar</button>
                                <a asp-action="Consultar" asp-controller="ProductoPrueba" class="btn btn-warning" href="@Url.Action("Consultar","ProductoPrueba")">Consultar</a>
                            </fieldset>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
</body>
</html>

Prueba/Views/ProductoPrueba/RealizarCompra.cshtml
@{
    ViewBag.Title = "RealizarCompra";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>RealizarCompra</h2>